entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/{{env "CERT"}}
        keyFile: /certs/{{env "KEY"}}
  certificates:
    - certFile: /certs/{{env "CERT"}}
      keyFile: /certs/{{env "KEY"}}
      stores:
        - default

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /config
    watch: true

api:
  insecure: true
  dashboard: true
